version: '3.8'

services:
  myapp:
    image: docker.io/bitnami/symfony:1
    ports:
      - '8000:8000'
    volumes:
      - './:/app'
    depends_on:
      - mariadb
    container_name: myapp
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    ports:
      - "3306:3306"
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    container_name: mariadb