version: '3.8'

services:
  myapp:
    image: docker.io/bitnami/symfony:1
    ports:
      - '8000:8000'
    volumes:
      - './:/app'
    environment:
      - SYMFONY_PROJECT_NAME=myapp
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MARIADB_USER=rootapi
      - MARIADB_PASSWORD=rootapi
      - MARIADB_DATABASE=api_platform
    depends_on:
      - mariadb
    container_name: myapp
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    ports:
      - "3306:3306"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=rootapi
      - MARIADB_PASSWORD=rootapi
      - MARIADB_DATABASE=api_platform
    container_name: mariadb